### ISSUE TITLE
quick question

### ISSUE THREAD

**Issue by colinricardo** [jcs224/oak_sessions#40]
just making an issue for this question (i usually dont get notifs on comments on github): https://github.com/jcs224/oak_sessions/commit/3d7495b7ffdb9ceea6f9dd00a4c7d6ef1de643f6

**Comment by jcs224** [comment]
I should have mentioned in the docs that session fixation mitigation doesn't work with the CookieStore, because the session ID isn't even used for CookieStore, making it irrelevant. I'm sure there's a solution to this, just haven't come up with one.

If avoiding session fixation is important to you, I recommend using a different storage driver for now until this is resolved.

**Comment by jcs224** [comment]
After a bit of research, it's not possible to rotate a session key with pure cookie storage. Readme has been updated.

See the [iron-session](https://github.com/vvo/iron-session#what-are-the-drawbacks) docs for a more detailed explanation.
